services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 5

  auth:
    build: 
      context: ./auth-service
      args:
        AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT:-8001}
        GO_VERSION: ${GO_VERSION:-1.26}
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CONFIG_PATH: /app/config/config.yml
      JWT_SECRET: ${JWT_SECRET}
      SERVICE_PORT: ${AUTH_SERVICE_PORT:-8001}
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}

  comm:
    build: 
      context: ./communication-service
      args:
        COMM_SERVICE_PORT: ${COMM_SERVICE_PORT:-8002}
        GO_VERSION: ${GO_VERSION:-1.26}
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      SERVICE_PORT: ${COMM_SERVICE_PORT:-8002}
    ports:
      - ${COMM_SERVICE_PORT}:${COMM_SERVICE_PORT}

  gateway:
    build: 
      context: ./api-gateway
      args:
        API_GATEWAY_PORT: ${API_GATEWAY_PORT:-8000}
        GO_VERSION: ${GO_VERSION:-1.26}
    depends_on: [auth, comm]
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CONFIG_PATH: /app/config/config.yml
      JWT_SECRET: ${JWT_SECRET}
      SERVICE_PORT: ${API_GATEWAY_PORT:-8000}
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}

volumes:
  pgdata:
